'use client';

import { useEffect, useMemo, useState } from 'react';

type Product = { id: number; name: string; category: string; price: number; wait: string; badge?: string; emoji: string; color: string; sizes?: string };
const products: Product[] = [
  { id: 1, name: 'Satin knot bag', category: 'Bags', price: 18500, wait: '3–4 weeks', badge: 'Best seller', emoji: '👜', color: 'rose', sizes: 'One size' },
  { id: 2, name: 'Cloud slide sandals', category: 'Shoes', price: 12000, wait: '4–5 weeks', badge: 'New in', emoji: '🩴', color: 'butter', sizes: '36–41' },
  { id: 3, name: 'Soft knit co-ord', category: 'Fashion', price: 26000, wait: '3–4 weeks', emoji: '👚', color: 'sage', sizes: 'S–XL' },
  { id: 4, name: 'Everyday mini tote', category: 'Bags', price: 15000, wait: '4–5 weeks', emoji: '👛', color: 'sky', sizes: 'One size' },
  { id: 5, name: 'Gold link watch', category: 'Accessories', price: 17500, wait: '3–4 weeks', badge: 'Trending', emoji: '⌚', color: 'peach', sizes: 'Adjustable' },
  { id: 6, name: 'Ribbed lounge set', category: 'Fashion', price: 22000, wait: '4–5 weeks', emoji: '🧺', color: 'lavender', sizes: 'S–XL' },
];
const naira = (amount: number) => `₦${amount.toLocaleString('en-NG')}`;
const featuredProducts = products.slice(0, 2);

export default function Home() {
  const [activeCategory, setActiveCategory] = useState('All items');
  const [cart, setCart] = useState<Product[]>([]);
  const [selected, setSelected] = useState<Product | null>(null);
  const [showCart, setShowCart] = useState(false);
  const [showFeatured, setShowFeatured] = useState(false);
  const [notice, setNotice] = useState('');
  const filtered = useMemo(() => activeCategory === 'All items' ? products : products.filter((p) => p.category === activeCategory), [activeCategory]);
  const total = cart.reduce((sum, item) => sum + item.price, 0);
  useEffect(() => { const timer = window.setTimeout(() => setShowFeatured(true), 900); return () => window.clearTimeout(timer); }, []);
  function addToCart(product: Product) { setCart((current) => [...current, product]); setNotice(`${product.name} added to your order`); window.setTimeout(() => setNotice(''), 2800); }

  return <main>
    <div className="announcement"><span className="spark">✦</span> New drops land every Sunday <span className="announcement-link">Join our WhatsApp community →</span></div>
    <nav className="nav shell"><a className="brand" href="#top" aria-label="AD Imports home"><span className="brand-mark">AD</span><span>AD <em>Imports</em></span></a><div className="nav-links"><a href="#shop">Shop</a><a href="#how-it-works">How it works</a><a href="#about">About us</a></div><button className="cart-button" onClick={() => setShowCart(true)} aria-label={`Open order bag, ${cart.length} items`}><span>Order bag</span><b>{cart.length}</b></button></nav>
    <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow">Thoughtfully sourced · Delivered to Nigeria</p><h1>Good finds.<br /><i>Better timing.</i></h1><p className="hero-description">Your shortcut to the things you&apos;ll love. Shop curated finds from China, placed on preorder and delivered straight to you.</p><div className="hero-actions"><a className="button button-dark" href="#shop">Explore the drop <span>↘</span></a><a className="text-link" href="#how-it-works">What is preorder? <span>→</span></a></div><div className="trust-row"><span>◉</span> Trusted by 200+ happy shoppers</div></div><div className="hero-art" aria-label="A curated selection of items from the latest drop"><div className="sun-shape" /><div className="art-label label-top">Latest drop<br /><strong>01 / 06</strong></div><div className="art-card art-card-main"><div className="art-emoji">👜</div><span>the everyday edit</span></div><div className="art-card art-card-small"><div className="art-emoji">⌚</div><span>little luxuries</span></div><div className="scribble">made<br />for you <span>↗</span></div><div className="art-sticker">PRE<br />ORDER</div></div></section>
    <section className="ticker"><div className="ticker-inner"><span>Curated from China</span><b>✦</b><span>Made for your everyday</span><b>✦</b><span>Delivery across Nigeria</span><b>✦</b><span>Curated from China</span><b>✦</b></div></section>
    <section className="shop-section shell" id="shop"><div className="section-heading"><div><p className="eyebrow">The latest edit</p><h2>Find your next <i>favourite.</i></h2></div><p className="section-note">Small batches. Better finds.<br />Once they&apos;re gone, they&apos;re gone.</p></div><div className="category-row">{['All items', 'Fashion', 'Bags', 'Shoes', 'Accessories'].map((category) => <button key={category} className={activeCategory === category ? 'active' : ''} onClick={() => setActiveCategory(category)}>{category}</button>)}</div><div className="product-grid">{filtered.map((product) => <article className="product-card" key={product.id}><button className={`product-visual ${product.color}`} onClick={() => setSelected(product)} aria-label={`View ${product.name}`}><span className="product-tag">{product.badge || 'Preorder'}</span><span className="product-emoji">{product.emoji}</span><span className="quick-view">View item ↗</span></button><div className="product-info"><div><h3>{product.name}</h3><p>{product.sizes} <span>·</span> Arrives in {product.wait}</p></div><strong>{naira(product.price)}</strong></div><button className="add-button" onClick={() => addToCart(product)}>Add to order <span>+</span></button></article>)}</div></section>
    <section className="how-section" id="how-it-works"><div className="shell"><div className="section-heading light-heading"><div><p className="eyebrow">No surprises here</p><h2>Preorder, made <i>simple.</i></h2></div><p className="section-note">We make the wait worth it<br />with clear timelines.</p></div><div className="steps"><div className="step"><span>01</span><h3>Pick your find</h3><p>Browse our current drop and choose something you love. Every item shows its expected arrival time.</p></div><div className="step"><span>02</span><h3>Place your order</h3><p>Pay securely in naira. We combine orders so you get better prices on beautiful things.</p></div><div className="step"><span>03</span><h3>We bring it home</h3><p>Your item travels from China to Nigeria. We&apos;ll keep you updated every step of the way.</p></div></div><div className="timeline"><span>Order closes</span><b>→</b><span>Ships from China</span><b>→</b><span>Arrives in Nigeria</span></div></div></section>
    <section className="about-section shell" id="about"><div className="about-art"><div className="about-note">a little<br />something<br /><i>special</i> ✦</div><div className="about-shape">✿</div></div><div className="about-copy"><p className="eyebrow">A note from AD</p><h2>Nice things,<br /><i>fairly found.</i></h2><p>AD Imports started with a love for the little things that make an ordinary day feel special. We search for them across China so you don&apos;t have to — bringing them to Nigeria in small, thoughtful drops.</p><a className="text-link" href="https://wa.me/2348000000000">Say hello on WhatsApp <span>↗</span></a></div></section>
    <footer className="footer"><div className="shell footer-inner"><a className="brand light-brand" href="#top"><span className="brand-mark">AD</span><span>AD <em>Imports</em></span></a><p>Good finds for your everyday.</p><div className="footer-links"><a href="#shop">Shop the drop</a><a href="#how-it-works">How it works</a><a href="mailto:hello@adimports.ng">hello@adimports.ng</a></div></div><div className="shell footer-bottom"><span>© 2026 AD Imports</span><span>Made for Nigeria, sourced with care.</span></div></footer>
    {notice && <div className="toast" role="status">✓ {notice} <button onClick={() => setShowCart(true)}>View bag</button></div>}
    {showFeatured && <div className="modal-backdrop featured-backdrop" onClick={() => setShowFeatured(false)}><div className="featured-modal" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={() => setShowFeatured(false)} aria-label="Close weekly picks">×</button><div className="featured-intro"><p className="eyebrow">This week at AD</p><h2>Little <i>luxuries.</i><br />Specially picked.</h2><p>Two lovely finds we think you&apos;ll want to know about. Available on preorder for this week only.</p></div><div className="featured-grid">{featuredProducts.map((product) => <div className="featured-card" key={product.id}><button className={`featured-visual product-visual ${product.color}`} onClick={() => { setSelected(product); setShowFeatured(false); }}><span className="product-emoji">{product.emoji}</span></button><div className="featured-details"><div><h3>{product.name}</h3><p>Arrives in {product.wait}</p></div><strong>{naira(product.price)}</strong></div><button className="featured-add" onClick={() => { addToCart(product); setShowFeatured(false); }}>Add to order +</button></div>)}</div><button className="text-link featured-dismiss" onClick={() => setShowFeatured(false)}>I&apos;ll browse for now <span>→</span></button></div></div>}
    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="modal" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={() => setSelected(null)} aria-label="Close">×</button><div className={`modal-visual product-visual ${selected.color}`}><span className="product-emoji">{selected.emoji}</span></div><p className="eyebrow">{selected.category} · {selected.badge || 'Preorder'}</p><h2>{selected.name}</h2><p className="modal-price">{naira(selected.price)}</p><p className="modal-copy">A lovely addition to your everyday rotation. This item is available on preorder and is expected to arrive in Nigeria in <strong>{selected.wait}</strong>.</p><button className="button button-dark full-button" onClick={() => { addToCart(selected); setSelected(null); }}>Add to order <span>+</span></button></div></div>}
    {showCart && <div className="modal-backdrop" onClick={() => setShowCart(false)}><aside className="cart-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">Your order bag</p><h2>{cart.length ? `${cart.length} ${cart.length === 1 ? 'item' : 'items'}` : 'It’s feeling light'}</h2></div><button className="close-button" onClick={() => setShowCart(false)} aria-label="Close order bag">×</button></div>{cart.length ? <><div className="cart-items">{cart.map((item, index) => <div className="cart-item" key={`${item.id}-${index}`}><div className={`cart-thumb ${item.color}`}>{item.emoji}</div><div><h3>{item.name}</h3><p>{item.wait} · {naira(item.price)}</p></div></div>)}</div><div className="cart-total"><span>Estimated total</span><strong>{naira(total)}</strong></div><a className="button button-dark full-button" href={`https://wa.me/2348000000000?text=${encodeURIComponent(`Hello AD Imports! I would like to preorder: ${cart.map((item) => item.name).join(', ')}. Estimated total: ${naira(total)}.`)}`}>Continue on WhatsApp <span>↗</span></a><p className="drawer-footnote">We&apos;ll confirm availability and payment details with you.</p></> : <div className="empty-cart"><div>✦</div><p>Your saved finds will<br />show up here.</p><a href="#shop" className="text-link" onClick={() => setShowCart(false)}>Explore the drop →</a></div>}</aside></div>}
  </main>;
}

